_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
                - 11
                - 12
                - 41
                - 45
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 12
                - 41
                - 45
                - 49
                - 51
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.15
            "5": 0.19.11
            "6": 4.53.2
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
assets_base_dir:
    value: ./assets
batch_size:
    value: 32
checkpoint_base_dir:
    value: ./checkpoints
data:
    value:
        action_sequence_keys:
            - action
        assets:
            asset_id: null
            assets_dir: null
        base_config:
            action_sequence_keys:
                - actions
            action_space: null
            asset_id: null
            data_transforms:
                inputs: []
                outputs: []
            datasets: []
            model_transforms:
                inputs: []
                outputs: []
            norm_stats: null
            prompt_from_task: true
            repack_transforms:
                inputs: []
                outputs: []
            repo_id: null
            rlds_data_dir: null
            use_quantile_norm: false
        default_prompt: move the object smoothly
        repack_transforms:
            inputs:
                - structure:
                    actions: action
                    images:
                        left_eye: observation.images.left_eye
                        left_wrist: observation.images.left_wrist
                        right_eye: observation.images.right_eye
                        right_wrist: observation.images.right_wrist
                    prompt: prompt
                    state: observation.state
            outputs: []
        repo_id: zzk/brx_act
        use_delta_joint_actions: true
ema_decay:
    value: 0.99
exp_name:
    value: brx_23d
freeze_filter:
    value: Nothing()
fsdp_devices:
    value: 1
keep_period:
    value: 5000
log_interval:
    value: 100
lr_schedule:
    value:
        decay_lr: 2.5e-06
        decay_steps: 30000
        peak_lr: 2.5e-05
        warmup_steps: 1000
model:
    value:
        action_dim: 32
        action_expert_variant: gemma_300m
        action_horizon: 16
        discrete_state_input: true
        dtype: bfloat16
        max_token_len: 200
        paligemma_variant: gemma_2b
        pi05: true
        pytorch_compile_mode: max-autotune
name:
    value: pi05_brx_finetune
num_train_steps:
    value: 30000
num_workers:
    value: 2
optimizer:
    value:
        b1: 0.9
        b2: 0.95
        clip_gradient_norm: 1
        eps: 1e-08
        weight_decay: 1e-10
overwrite:
    value: true
policy_metadata:
    value: null
project_name:
    value: openpi
pytorch_training_precision:
    value: bfloat16
pytorch_weight_path:
    value: null
resume:
    value: false
save_interval:
    value: 1000
seed:
    value: 42
wandb_enabled:
    value: true
weight_loader:
    value:
        params_path: gs://openpi-assets/checkpoints/pi05_base/params
